version: '2'

services:
  app:
    image: nextcloud
    container_name: "${DOMAIN_NAME}_nextcloud"
    ports:
      -  "${HTTP_IP}:${HTTP_PORT}:80"
    volumes:
      - "${DATA_PATH}:/var/www/html"
    restart: always

